# Generated by Django 6.0.4 on 2026-05-01 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата'),
        ),
    ]
