# Generated by Django 6.0.4 on 2026-05-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_currencyrate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюти')),
                ('name', models.CharField(max_length=100, verbose_name='Назва валюти')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
                'ordering': ('code',),
            },
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='name',
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rates.currency', verbose_name='Валюта'),
        ),
    ]
